baseurl = "https://johnqu.site/"
languageCode = "en-us"
title = "John | 曲"
theme = "hugo-ivy"
# googleAnalytics = "UA-154716505-1"
# disqusShortname = "John Qu"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
rssLimit = 100

[permalinks]
    cn = "/cn/:year/:month/:slug/"
    en = "/en/:year/:month/:slug/"
    cn-note = "/cn-note/:year/:month/:slug/"
    mit6000 = "/mit6000/:year/:month/:slug/"
    ref = "/ref/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 3
[[menu.main]]
    name = "文章"
    url = "/cn/"
    weight = 4
[[menu.main]]
    name = "笔记"
    url = "/cn-note/"
    weight = 5
    
[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
[[menu.en]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.en]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.en]]
    name = "中文文章"
    url = "/cn/"
    weight = 6
    
[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn]]
    name = "文章"
    url = "/cn-note/"
    weight = 3
[[menu.cn]]
    name = "笔记"
    url = "/cn-note/"
    weight = 4
[[menu.cn]]
    name = "分类"
    url = "/categories/"
    weight = 5
[[menu.cn]]
    name = "标签"
    url = "/tags/"
    weight = 6
[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 7
    
[[menu.cn-note]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn-note]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn-note]]
    name = "文章"
    url = "/cn/"
    weight = 3
[[menu.cn-note]]
    name = "笔记"
    url = "/cn-note/"
    weight = 4
[[menu.cn-note]]
    name = "分类"
    url = "/categories/"
    weight = 5
[[menu.cn-note]]
    name = "标签"
    url = "/tags/"
    weight = 6
[[menu.cn-note]]
    name = "MIT 6000"
    url = "/MIT6000/"
    weight = 7
[[menu.cn-note]]
    name = "Reference"
    url = "/ref/"
    weight = 8

[[menu.MIT6000]]
    name = "Home"
    url = "/MIT6000/"
    weight = 1
[[menu.MIT6000]]
    name = "分类"
    url = "/categories/"
    weight = 2
[[menu.MIT6000]]
    name = "标签"
    url = "/tags/"
    weight = 3
[[menu.MIT6000]]
    name = "John Qu"
    url = "/"
    weight = 4
    
[[menu.Reference]]
    name = "Home"
    url = "/MIT6000/"
    weight = 1
[[menu.Reference]]
    name = "分类"
    url = "/categories/"
    weight = 2
[[menu.Reference]]
    name = "标签"
    url = "/tags/"
    weight = 3
[[menu.Reference]]
    name = "John Qu"
    url = "/"
    weight = 4


[params]
    description = "Reflection in Transition"
    footer = "&copy; [John Qu](https://johnqu.site) 2020 - 2025 | [Github](https://github.com/john-qu)"
    customJS = [
    "js/fix-toc.js",
    "js/center-img.js",
    "js/right-quote.js",
    "js/no-highlight.js",
    "js/fix-footnote.js",
    "js/math-code.js",
    "js/external-link.js",
    "js/alt-title.js",
    "js/header-link.js"
    ]
    githubContentURL = "https://github.com/john-qu/johnqu.site/edit/master/content/"
    show_toc = true
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    
  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = 'AmxF4njTuN8SqLiIcMpN0UAN-MdYXbMMI'
  appKey = 'OdEwQhq4NpYKfrOsDeoo0ivQ'
  avatar = 'mp' 
  placeholder = '你给我留言，我会收到邮件提醒。你留下邮箱，我才有可能给你回复提醒。这里可以用 markdown 语法排版，按 Ctrl + Enter 组合键发送。'
  visitor = false
buildDrafts = false
buildFuture = false
buildExpired = false

